### PR TITLE
Project file updates and removal of redundant files

### PR DESCRIPTION
**Pull request by jewelsea**
Updates the followme.fx pom.xml file to work with recent maven and afterburner.fx releases.

Removes redundant fxml.bak files from the followme.fx project.

### CODE REVIEW

**Comment by AdamBien** [comment]
Thanks! But please look at igniter.fx. It is a fork of this project. The output of igniter.fx is a maven archetype. See: http://www.adam-bien.com/roller/abien/entry/afterburner_fx_1_2_and

**Comment by jewelsea** [comment]
This is all really confusing, the afterburner.fx readme (https://github.com/AdamBien/afterburner.fx) refers directly to only (https://github.com/AdamBien/followme.fx), and the igniter.fx archetype readme (https://github.com/AdamBien/igniter.fx/tree/master/src/main/resources/archetype-resources) also refers to (https://github.com/AdamBien/followme.fx).

I am sometimes asked about dependency injection frameworks and JavaFX (e.g. http://stackoverflow.com/questions/20389567/how-to-initialize-javafx-controllers-with-the-same-model-object).  afterburner.fx seems like a decent solution, but I am hesitant to recommend it given issues such as these.

IMO, these kinds of projects should be standalone and not rely on references and documentation in a blog.

**Comment by AdamBien** [comment]
Followme.fx came first. Then I created the igniter.fx as a standalone project to keep followme.fx clean as a standalone example. Maven archetype creation, as well as, the submission to maven central comes with significant bloat to the pom.xml and code structure. 

Because the structure is so different, I'm integration-testing afterburner.fx with igniter.fx. Sometimes I do not back port the changes to followme.fx.

I don't like duplication. If I post something on my blog, I don't copy the content to github and vice versa.

Don't forget the screencasts, they are hosted on: http://www.youtube.com/user/bienadam :-)

This link: https://github.com/AdamBien/igniter.fx/tree/master/src/main/resources/archetype-resources is an copy-and-paste error. I'm going to fix it (remove it) right now.

**Comment by AdamBien** [comment]
README.md fixed. Thanks for the hint! Now everything should be crystal clear :-)

**Pull request merged**
